version: '3.8'
services:
  api:
    build:
      context: ./apps/api/
    container_name: api
    env_file:
      - ./apps/api/.env
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - ./apps/api/.env
      - ./apps/api/.env.production
    volumes:
      - ./apps/api/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: ./apps/web/
    env_file:
      - ./apps/web/.env
    container_name: web
    ports:
      - $VITE_APP_PORT:$VITE_APP_PORT

  caddy:
    image: caddy:2
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
      - "./data:/data"
      - "./config:/config"
    ports:
      - "80:80"
      - "443:443"
  
volumes:
  pgdata:
