version: '3.8'
services:
  api:
    build:
      context: ./apps/api/
    container_name: api
    ports:
      - 4000:4000
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - ./apps/api/.env.production
    volumes:
      - ./apps/api/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: ./apps/web/
    container_name: web
    ports:
      - '4200:4200'

  caddy:
    image: caddy:2
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
      - "./data:/data"
      - "./config:/config"
    ports:
      - "80:80"
      - "443:443"
  
volumes:
  pgdata:
