version: '3.8'
services:
  api:
    build:
      context: ./apps/api/
    container_name: api 
    ports:
      - 4000:80
    networks:
      - backend
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - 5432:5432
    networks:
      - backend
    env_file:
      - ./apps/api/.env.production
    volumes:
      - ./apps/api/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: ./apps/web/
    container_name: web 
    ports:
      - '4200:80'
    networks:
      - frontend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - web
    networks:
      - frontend
      - backend

volumes:
  pgdata:

networks:
  frontend:
  backend:
