version: '3.8'
services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestapi 
    ports:
      - 4000:4000
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgresprisma
    ports:
      - 5432:5432
    env_file:
      - .env.prod
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql