version: '3.8'
services:
  nestapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestapi 
    ports:
      - 4000:4000
    depends_on:
      - postgres
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - nestapi
  postgres:
    image: postgres:13
    container_name: postgresprisma
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql