version: "2"
services:
  nest-app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
    depends_on:
      - postgres